name: buildWin

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    permissions: write-all
    runs-on: windows-latest

    steps:
      - name: check
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Haxe
        uses: krdlab/setup-haxe@v2
        with:
          haxe-version: 4.3.7

      - name: Download Libary
        run: ./buildwindow.bat --dllib
        shell: cmd

      - name: Setup Lime First
        run: haxelib run lime setup -alias -y -nocffi

      - name: Calculate Total Commit Count
        id: count_commits
        shell: bash
        run: |
          TOTAL_COMMITS=$(git rev-list --count HEAD)
          echo "TOTAL_COMMITS=$TOTAL_COMMITS" >> $GITHUB_ENV

      - name: Then Build it
        run: ./buildwindow.bat --build -release -D commit=${{ env.TOTAL_COMMITS }}
        shell: cmd

      # for debug
      - name: dir
        run: dir

      - name: Upload Build
        uses: actions/upload-artifact@v7
        with:
          name: Build
          path: ./export/windows/bin
